version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-security:
        applies-to: security-updates
        patterns:
          - "*"